[tool.black]
line-length=120
target-version=['py39']

[tool.bandit]
exclude_dirs = [".venv"]

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
follow_imports = "silent"
